Implement pgTAP test cases for validator
Classification: Implementation
Content:
- Implemented test cases for tibero fdw validator
- Changed pgTAP test case files name (removed numbering) for better maintainability
- Added hidden parameter flag (so that hidden parameters are not displayed in error message)
- Added owner_name parameter to foreign table validator
Reproduction steps:
- Using pgTAP test cases
cd sql
./run_test.sh option_validator.sql

- Not displaying hidden parameters
/* use wrong option name to any DDL */
/* PRIOR TO THIS COMMIT, hidden parameters like sleep_on_sig and use_fb_query were shown in error message */
create server test_server foreign data wrapper tibero_fdw
options (wrong_option 'wrong option value');
ERROR:  invalid option "wrong_option"
HINT:  Valid options in this context are: host, port, dbname, fetch_size, sleep_on_sig, use_fb_query

/* AFTER THIS COMMIT, hidden parameters are not displayed */
create server test_server foreign data wrapper tibero_fdw
options (wrong_option 'wrong option value');
ERROR:  invalid option "wrong_option"
HINT:  Valid options in this context are: host, port, dbname, fetch_size

- Added owner_name to foreign table options
/* BEFORE THIS COMMIT, owner_name option was not acceptable */
create foreign table test_tbl (c1 int) server tibero_server
options (owner_name 'tmax', table_name 'test');
ERROR:  invalid option "owner_name"

/* AFTER THIS COMMIT, owner_name option is acceptable */
create foreign table test_tbl (c1 int) server tibero_server
options (owner_name 'tmax', table_name 'test');
CREATE FOREIGN TABLE