Added required option validation logic to validator
Classification: Functional Improvement
Content:
- Added required option validation logic
- Added and modified test cases for required option validation
- Refactoring for easier maintainability
Reproduction steps:
- Required option validation
```sql
/* PRIOR TO THIS COMMIT, validator accepted missing required options */
/* dbname is required but it's missing */
CREATE SERVER tibero_server FOREIGN DATA WRAPPER tibero_fdw
OPTIONS (host 'localhost', port '5432');
CREATE SERVER
/* dropping required option was possible */
ALTER SERVER tibero_server OPTIONS (drop host);

/* AFTER THIS COMMIT, validator checks whether required options are all there */
/* when a required option is missing, error is thrown with a hint of which options are needed */
CREATE SERVER tibero_server FOREIGN DATA WRAPPER tibero_fdw
OPTIONS (host 'localhost', port '5432');
ERROR:  insufficient options
HINT:  The following required options are missing: dbname

CREATE SERVER tibero_server FOREIGN DATA WRAPPER tibero_fdw
OPTIONS (host 'localhost', port '5432', dbname 'testdb');
CREATE SERVER

/* when a required option is being dropped, error is thrown */
ALTER SERVER tibero_server OPTIONS (drop host);
ERROR:  insufficient options
HINT:  The following required options are missing: host
```